version: '3.4'

services:
  database_container:
    image: mysql
    container_name: "database_container"
    environment:
      - MYSQL_DATABASE=VideoStoreDB
      - MYSQL_USER=sysmanager
      - MYSQL_PASSWORD=vid30club
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    ports:
      - "3018:3306"
    volumes:
      - "database_vol:/var/lib/mysql"
  dockertraining_compose_fernando_castellanos:
    image: ${DOCKER_REGISTRY-}dockertrainingcomposefernandocastellanos
    container_name: "api_container"
    build:
      context: .
      dockerfile: dockertraining_compose_fernando_castellanos/Dockerfile
    ports:
      - "8091:80"
    environment:
      - ConnectionStrings:VideoStoreDB=Server=database_container;Port=3306;Database=VideoStoreDB; Uid=sysmanager; Pwd=vid30club
    depends_on:
      - database_container
volumes:
  database_vol:
