// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dockertraining_compose_fernando_castellanos.Models;

namespace dockertraining_compose_fernando_castellanos.Migrations
{
    [DbContext(typeof(VideoStoreContext))]
    partial class VideoStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("dockertraining_compose_fernando_castellanos.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Creative_Type")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Director")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Distributor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double?>("IMDB_Rating")
                        .HasColumnType("double");

                    b.Property<int?>("IMDB_Votes")
                        .HasColumnType("int");

                    b.Property<string>("MPAA_Rating")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Major_Genre")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("Production_Budget")
                        .HasColumnType("int");

                    b.Property<string>("Release_Date")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("Rotten_Tomatoes_Rating")
                        .HasColumnType("int");

                    b.Property<int?>("Running_Time_min")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("US_DVD_Sales")
                        .HasColumnType("int");

                    b.Property<int?>("US_Gross")
                        .HasColumnType("int");

                    b.Property<long?>("Worldwide_Gross")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
